spring:
  profiles:
    active: local

---
spring:
  profile: local
kafka:
  bootstrap.servers: 127.0.0.1:9092

  producer:
    acks: 1
    retries: 10

  consumer:
    group.id: my-avro-consumer
    enable.auto.commit: false
    auto.offset.reset: latest

avro:
  schema.registry.url: http://127.0.0.1:8081
  specific.avro.reader: true

logging:
  level:
    root: ERROR
    com.leightek: DEBUG